"""Small local operator dashboard; it deliberately exposes aggregate state only."""

from __future__ import annotations

HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Secure MCP Gateway</title>
<style>
:root{--bg:#07111f;--panel:#0d1b2e;--line:#203653;--text:#e7eef9;--muted:#9eb0c9;--green:#35d399;--amber:#f6c35b;--red:#fb7185;--blue:#66a8ff}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#15365a 0,#07111f 44%);color:var(--text);font:15px ui-sans-serif,system-ui,-apple-system,sans-serif}
main{max-width:1160px;margin:auto;padding:38px 28px 54px}.eyebrow{color:var(--blue);letter-spacing:.12em;font-weight:700;font-size:12px}.head{display:flex;justify-content:space-between;gap:24px;align-items:end}.head h1{margin:7px 0;font-size:38px}.head p{margin:0;color:var(--muted);max-width:670px;line-height:1.5}.live{border:1px solid #1f5c53;background:#0a2929;color:var(--green);padding:9px 12px;border-radius:999px;white-space:nowrap;font-weight:700}
.flow{margin:28px 0;background:rgba(13,27,46,.86);border:1px solid var(--line);padding:16px 20px;border-radius:14px;color:#c7d6eb;display:flex;gap:11px;align-items:center;flex-wrap:wrap}.flow b{color:var(--blue)}.arrow{color:#5f789c}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.section{background:rgba(13,27,46,.9);border:1px solid var(--line);border-radius:14px}.card{padding:19px}.card .label{color:var(--muted);font-size:13px}.card .value{font-size:29px;font-weight:800;margin-top:8px}.card .hint{font-size:12px;color:var(--muted);margin-top:5px}.section{margin-top:16px;padding:22px}.section h2{font-size:18px;margin:0 0 14px}.cols{display:grid;grid-template-columns:1.25fr .75fr;gap:16px}.event{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #19304d}.event:last-child{border:0}.event b{font-size:13px}.count{font-weight:800;color:var(--blue)}.control{padding:12px;border:1px solid #214364;border-radius:10px;margin:9px 0}.control strong{display:block}.good{color:var(--green)}.warning{color:var(--amber)}.danger{color:var(--red)}.foot{margin-top:20px;color:var(--muted);font-size:12px;line-height:1.5}
@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}.cols{grid-template-columns:1fr}.head{display:block}.live{display:inline-block;margin-top:16px}}
</style></head><body><main>
<div class="head"><div><div class="eyebrow">LOCAL-FIRST · ZERO-TRUST MCP OPERATIONS</div><h1>Secure MCP Gateway</h1><p>Live governed MCP evidence. This dashboard shows safe aggregates only—never bearer tokens, raw tool inputs, or unredacted upstream responses.</p></div><div class="live">● <span id="state">CONNECTING</span></div></div>
<div class="flow"><b>Signed identity</b><span class="arrow">→</span><b>Filtered tools/list</b><span class="arrow">→</span><b>OPA policy</b><span class="arrow">→</span><b>Approval</b><span class="arrow">→</span><b>Live MCP call</b><span class="arrow">→</span><b>Audit</b></div>
<div class="grid"><div class="card"><div class="label">Audit events</div><div class="value" id="events">—</div><div class="hint">Persisted SQLite evidence</div></div><div class="card"><div class="label">Approved protected writes</div><div class="value" id="approved">—</div><div class="hint">Exact action hash required</div></div><div class="card"><div class="label">Policy/security denials</div><div class="value" id="denied">—</div><div class="hint">No upstream call occurred</div></div><div class="card"><div class="label">Write kill switch</div><div class="value" id="kill">—</div><div class="hint">Governed writes only</div></div></div>
<div class="cols"><section class="section"><h2>Live audit event counts</h2><div id="event-list"><div class="event">Loading evidence…</div></div></section><section class="section"><h2>Enforced boundaries</h2><div class="control"><strong class="good">✓ Delegated identities</strong>Agent must carry a signed human delegator.</div><div class="control"><strong class="good">✓ OPA parameter policy</strong>Cross-team access and unsafe writes are blocked.</div><div class="control"><strong class="good">✓ Exact approvals</strong>Changed or replayed protected actions are rejected.</div><div class="control"><strong class="good">✓ Response redaction</strong>Synthetic secret output is removed before return.</div></section></div>
<div class="foot">Auto-refreshes every 5 seconds · Project-local gateway and fixtures · Simulation boundary: fixture MCP tools represent infrastructure services; no cloud provider is controlled.</div>
</main><script>
function n(c,k){return c[k]||0}async function refresh(){try{let d=await fetch('/api/v1/dashboard').then(r=>r.json()),c=d.audit_counts;document.querySelector('#state').textContent='GATEWAY HEALTHY';document.querySelector('#events').textContent=d.total_events;document.querySelector('#approved').textContent=n(c,'PLAN_APPROVED');document.querySelector('#denied').textContent=n(c,'TOOL_CALL_DENIED')+n(c,'WRITE_KILL_SWITCH_DENIED')+n(c,'STALE_OR_UNAPPROVED_ACTION');document.querySelector('#kill').innerHTML=d.writes_disabled?'<span class="danger">ACTIVE</span>':'<span class="good">OFF</span>';document.querySelector('#event-list').innerHTML=Object.entries(c).sort().map(([k,v])=>`<div class="event"><b>${k.replaceAll('_',' ')}</b><span class="count">${v}</span></div>`).join('')||'<div class="event">No activity yet.</div>'}catch(e){document.querySelector('#state').textContent='UNAVAILABLE'}}refresh();setInterval(refresh,5000)
</script></body></html>"""
